name: vitasense
description: Cook smarter. Waste less. Eat for your goals.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # SUPABASE
  supabase_flutter: ^2.5.0

  # AUTH — SOCIAL LOGIN
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  # NAVIGATION
  go_router: ^14.2.0

  # PŁATNOŚCI (RevenueCat — Apple IAP + Google Play)
  purchases_flutter: ^8.11.0

  # APARAT I ZDJĘCIA
  camera: ^0.11.0
  image_picker: ^1.1.2

  # RESPONSYWNOŚĆ
  flutter_screenutil: ^5.9.3

  # ANIMACJE
  flutter_animate: ^4.5.0

  # UI KOMPONENTY
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  native_glass_navbar: ^1.0.0

  # LOKALNE PRZECHOWYWANIE
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.0.0

  # NARZĘDZIA
  intl: ^0.20.2
  uuid: ^4.4.0
  collection: ^1.18.0
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  # ASSETS I FONTY
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.8
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # DEV DEPENDENCIES
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

dependency_overrides:
  analyzer: 6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/


flutter_native_splash:
  color: "#F5F5F5"
  image: ~
  color_dark: "#F5F5F5"
  android: true
  ios: true
